---
title: "Lesson 3: Simultaneity"
format: revealjs
title-slide-attributes:
  data-notes: |
    Hi everyone. It's good to see you all again! I'll quickly recap what we covered last time and then dive right into this lesson. Last time, we discussed the axioms of relativity and time dilation. Can someone remind me what the two axioms of relativity were? (All inertial reference frames equivalent, and the speed of light is constant.) And can someone remind me of what time dilation is and what the equation for time dilation is?
---

# Recap

## The Lorentz factor, $\gamma$

* A clock in motion appears to... run slow by a factor of $\gamma$.
* An object in motion appears... contracted along the direction of its length by a factor of $\gamma$.
* Where $\gamma=\class{fragment}{\frac{1}{\sqrt{1-(v/c)^2}}.}$

## Synchronization

* What is the challenge of having observers are different locations discuss their findings?

# The relativity of simultaneity

## Simultaneity

* Hopefully by now you've given up on trusting your intuition of space and time.
* So it should not come as a surprise that two observers can disagree on whether two events are simultaneous (i.e. occur at the same time)!

## Design an experiment

* Your turn: try to design an experiment where different observers would disagree on whether two events happened simultaneously or not.

## The procedure

* Place a lightbulb, initially off, in the middle of a train car of length $L$.
* Set the train in motion at speed $v$.
* Turn on the lightbulb.
* When does it arrive at the front of the train (Frank)?
* When does it arrive at the back (Beth)?

## The train perspective

* Let's add a third observer, Larry, at the center of the train, who controls the lightbulb.
* Frank’s, Beth’s, and Larry’s clocks are all synchronized.
* All three agree on the procedure:

  * When their clocks hit 0, Larry turns on the light.
  * When Frank receives a photon at the front of the train, he stops his clock.
  * When Beth receives a photon at the back of the train, she stops her clock.

* They all agree: the photons each travel $\frac{L}{2}$, and so Frank’s and Beth’s clocks both read $\frac{L/2}{c}$.

## The platform perspective

* Remember: all inertial frames agree on events, regardless of their relative motion.
	* A platform observer right next to Frank when he stops his clock will see it read $\frac{L/2}{c}$.
	* A separate platform observer right next to Beth when she stops her clock will see it read $\frac{L/2}{c}$.
* The “issue”: those two observers won't agree that Frank and Beth stop their clocks at the same time!
* Why not?

## The platform perspective

* Everyone agrees that the forward-moving and backward-moving photons have the same speed...
* but to those on the platform, the front of the train is moving _away_ from the forward-moving photon,
* and the back of the train is moving _towards_ the forward moving photon,
* and so platform observers will see Beth stop her clock before Frank!
* Takeaway 1: Events simultaneous in one frame are not simultaneous in other frames!

## The platform perspective

* But if Frank’s and Beth’s clocks are ticking at the same rate,
* and they both read the same value when they stop,
* and they stop at different times,
* they must not have been in sync to begin with!
* Takeaway 2: Clocks synchronized in one frame are not synchronized in other frames! [Whose clock is ahead?]{.fragment}

## Calculating the time difference

* The train has rest length $L$ and speed $v$.
* From the platform’s perspective, Frank and Beth are $\frac{L}{\gamma}$ apart.

## Calculating the time difference

* Frank:
	* Has initial position $+\frac{L}{2\gamma}$.
	* Is traveling with speed $+v$.
* Beth:
	* Has initial position $-\frac{L}{2\gamma}$.
	* Is traveling with speed $+v$.
* The photons:
	* Have initial position $0$.
	* Are traveling at speed $\pm c$.

## Calculating the time difference

* Supposing we're on the platform, right next to Larry when he turns on the lightbulb, then:
* The time when Frank and his photon meet is given by [$0+ct_F=+\frac{L}{2\gamma}+vt_F \to t_F=\frac{L}{2\gamma(c-v)}$.]{.fragment}
* The time when Beth and her photon meet is given by [$0-ct_B=-\frac{L}{2\gamma}+vt_B \to t_B=\frac{L}{2\gamma(c+v)}$.]{.fragment}

## Calculating the time difference

* The amount of time that the platform observes elapse between Beth stopping her clock and Frank stopping his clock is:

::: {.fragment}

$$
\begin{align*}
t_F-t_B&\class{fragment}{{}=\frac{L}{2\gamma(c-v)}-\frac{L}{2\gamma(c+v)}}\\
&\class{fragment}{{}=\frac{L}{2\gamma}\left(\frac{1}{c-v}-\frac{1}{c+v}\right)}\\
&\class{fragment}{{}=\frac{L}{2\gamma}\left(\frac{(c+v)-(c-v)}{(c-v)(c+v)}\right)}\\
&\class{fragment}{{}=\frac{L}{2\gamma}\left(\frac{2v}{c^2-v^2}\right)}\\
\end{align*}
$$

:::

## Calculating the time difference

$$
\begin{align*}
t_F-t_B&=\frac{L}{2\gamma}\left(\frac{2v}{c^2-v^2}\right)\\
&\class{fragment}{{}=\frac{L}{\gamma c^2}\left(\frac{v}{1-(v/c)^2}\right)}\\
&\class{fragment}{{}=\frac{L}{\gamma c^2}\left(v\gamma^2\right)}\\
&\class{fragment}{{}=\frac{Lv\gamma}{c^2}}
\end{align*}
$$


## Calculating the time difference

$$
\begin{align*}
t_F-t_B&=\frac{Lv\gamma}{c^2}
\end{align*}
$$


* This is how much time elapsed _according to us (on the platform)_.
* Frank and Beth are in motion, so their clocks are running slow by a factor of $\gamma$.
* So if $\frac{Lv\gamma}{c^2}$ time passes on _our_ clocks between Beth and Frank stopping their clocks...
* Then $\frac{Lv}{c^2}$ time passes on Frank’s clock.
* But remember — both clocks show the same time ($\frac{L}{2c}$) when the photon arrives!

## Conclusion

* Frank’s clock must have started out $\frac{Lv}{c^2}$ _behind_ Beth’s clock!
* Clocks separated by a distance $L$ and traveling at speed $v$, [and synchronized in their own frame,]{.fragment} [appear to differ by $\frac{Lv}{c^2}$,]{.fragment} [with the clock in front lagging behind the clock in the back — “leading clocks lag”.]{.fragment}


# Fin!
