---
title: "Lesson 5: The Lorentz Transform"
format: revealjs
---

# Recap

## Effects of relativity

* Time dilation: [a clock in motion appears to tick slower by a factor of $\gamma$]{.fragment}
* Length contraction: [an object in motion appears contracted along its direction of motion by a factor of $\gamma$]{.fragment}
* Relativity of simultaneity: [if two clocks are synchronized in their own frame, and separated by a distance $L$ in the direction of their motion, the front clock appears to lag behind the rear clock by $\frac{Lv}{c^2}$ (“leading clocks lag”)]{.fragment}

# The Lorentz transform

## Computational difficulties

* We've seen some exercises that required a lot of:
	* Thought
	* Care
	* Calculation
* This is annoying.
* Can we do better?

## A unified framework

* Wouldn't it be nice... [if we had some simple equations that let us “plug and chug”]{.fragment}
* The goal:
	* Given $x$ and $t$, find $x'$ and $t'$ [(I say it happened when/where — what do they say?)]{.fragment}
	* Given $x'$ and $t'$, find $x$ and $t$ [(They say it happened when/where — what do I say?)]{.fragment}
* In other words: a rote, mindless way to transform between coordinate systems in relative motion.

## The setup

* We have reference frames $F$ and $F'$.
* We will consider $F$ stationary.
* $F'$ has (relative) velocity $v$ in the $+x$ direction.
* $F$ and $F'$ have a common origin: at $t=t'=0$, their origins $O$ and $O'$ coincide ($x=x'=0$).
* $F'$ observes an event at $(x', t')$.
* What coordinates $(x,t)$ does $F$ ascribe to that event?

## The primed position component

1. Length contraction: $F$ observes the distance between $O'$ and $x'$ to be $\frac{x'}{\gamma}$.
1. At time $t$, $O'$ is at position $x=vt$.
1. So at time $t$, $F$ observes $x'$ at $x=vt+\frac{x'}{\gamma}$.
1. Solve for $x'$: [$x'=\gamma(x-vt)$.]{.fragment}

## The unprimed position component

1. Length contraction: $F'$ observes the distance between $O$ and $x$ to be $\frac{x}{\gamma}$.
1. At time $t'$, $O$ is at position $-vt'$.

	* Negative! — because $F$ is, relatively, moving in the opposite direction.

1. So at time $t'$, $F'$ observes $x$ at $x'=-vt'+\frac{x}{\gamma}$.
1. Solve for $x$: [$x=\gamma(x'+vt)$.]{.fragment}
1. Note: as we'd hope, the equations are the symmetric in unprimed and primed variables, with $v$ inverted.

## The primed time component

$$
\begin{align*}
x'&=-vt'+\frac{x}{\gamma}\\
x'&=\gamma(x-vt)\\
\class{fragment}{\gamma(x-vt)}&\class{fragment}{{}=-vt'+\frac{x}{\gamma}}\\
\class{fragment}{vt'}&\class{fragment}{{}=\frac{x}{\gamma}-\gamma(x-vt)}\\
\class{fragment}{t'}&\class{fragment}{{}=\left(\frac{1-\gamma^2}{\gamma v}\right)x+\gamma t}
\end{align*}
$$

## The primed time component

$$
\begin{align*}
t'&=\left(\frac{1-\gamma^2}{\gamma v}\right)x+\gamma t\\
&\class{fragment}{{}=\left(\frac{1-\frac{1}{1-(v/c)^2}}{\gamma v}\right)x+\gamma t}\\
&\class{fragment}{{}=\left(\frac{-(v/c)^2}{\gamma v (1-(v/c)^2)}\right)x+\gamma t}\\
&\class{fragment}{{}=\left(\frac{-(v/c)^2}{\gamma v} \gamma^2\right)x+\gamma t}\\
\end{align*}
$$

## The primed time component

$$
\begin{align*}
t'&=\left(\frac{-(v/c)^2}{\gamma v} \gamma^2\right)x+\gamma t\\
&\class{fragment}{{}=\gamma\left(t-\frac{vx}{c^2}\right)}
\end{align*}
$$

## The unprimed time component

* By identical logic, $t=\gamma\left(t'+\frac{vx'}{c^2}\right)$.
	* If you're interested, try to derive this on your own.
	* It's literally the same math, but starting with two expressions for $x$ instead of two expressions for $x'$.
* Key point: it's identical, with the primed and unprimed variables swapped, and $v$ negated.
* This is good: “no privileged reference frames” means we need all observers to agree on how to transform between coordinate systems.

## The Lorentz transform

$$
\begin{align*}
x'&=\gamma(x-vt)\\
t'&=\gamma\left(t-\frac{vx}{c^2}\right)\\
\\
x&=\gamma(x'+vt')\\
t&=\gamma\left(t'+\frac{vx'}{c^2}\right)
\end{align*}
$$

## A more elegant formulation:

* Let $\beta=\frac{v}{c}$.
* Use $ct$ and $ct'$ instead of $t$ and $t'$.

## A more elegant formulation:

::: {.fragment}
$$
\begin{align*}
x'&=\gamma(x-\beta ct)\\
ct'&=\gamma(ct-\beta x)\\
\\
x&=\gamma(x'+\beta ct')\\
ct&=\gamma(ct'+\beta x')
\end{align*}
$$
:::

* Not only are they symmetric in $v$, they're now symmetric in $x$ and $ct$.
* “The primed variable equals the unprimed variable minus $\beta$ times the other one, all times $\gamma$.”

# Interpreting the Lorentz transform

## Transformations are just lines

* Earlier, we alluded to how special relativity is “stunted”: [it can only deal with inertial reference frames (no acceleration, no gravity).]{.fragment}
* Now we see the manifestation of that: the Lorentz transform is a _linear transformation_ between coordinate systems.
* $x'$ and $t'$ are linear functions of $x$ and $t$.
* In other words, spacetime has to be “flat” (as opposed to curved) for special relativity to apply.

## Spacetime diagrams

::: {.r-stack}

<iframe src="../special-relativity-lessons/lesson-4/SpacetimeDiagram" width="1400" height="600" frameborder="true" ></iframe>

:::


# Using the Lorentz transform

## Deriving “leading clocks lag”

* In the primed frame, two (synchronized) clocks read $t'=0$. One is at $x'=0$, the other at $x'=L$.
* At $t=0$ in the unprimed frame, we don't (yet) know the time $t'$ on a clock at $x'=L$.
* But using $x'=\gamma(x-\beta ct)$, we get $x=\frac{L}{\gamma}$ (good).
* Then $t'=\gamma\left(t-\frac{v(L/\gamma)}{c^2}\right)=-\frac{vL}{c^2}$.
* Great! The leading clock does indeed lag behind the origin by $\frac{vL}{c^2}$.

## Io (5 min)

* A space probe will be sent to Io to record some data.
* The probe travels from Earth at a constant speed of $\frac{4}{5}c$. According to a clock on the probe, at this speed it takes ten hours to travel from Earth to Io.
* When the probe arrives at Io, it sends a single photon back to Earth to let us know it arrived safely.
* Q: According to us on Earth, how many hours after the probe leaves Earth should we expect the photon to arrive?
* A: $30\,\textrm{hrs}$.

::: {.notes}
Use the Lorentz transform!
:::

## Solution

* $\gamma=\frac{5}{3}$&nbsp;
* To the probe (primed frame):
	* Io reaches the origin of the primed frame at $t'=10\,\textrm{hrs}$.
	* The position of Io at that time is $x'=0$.
* Remember: in any given frame, the frame itself is stationary!

## Solution

* To the Earth:
	* The position of Io is $x=\gamma(x'+vt')=\frac{5}{3}(0+\frac{4}{5}c\cdot 10\,\textrm{hrs})=\frac{40}{3}c\,\textrm{hrs}$.
		* Technically this is only the position of Io when the probe arrives — why is it _always_ the position of Io?
	* The probe arrives at $t=\gamma(t'+\frac{vx'}{c^2})=\frac{5}{3}(10\,\textrm{hrs}+0)=\frac{50}{3}\,\textrm{hrs}$.

## Solution

* The time it takes the photon to reach Earth from Io is $\frac{x}{c}=\frac{40}{3}\,\textrm{hrs}$.
* Just add: $t_{\textrm{total}}=\left(\frac{40}{3}+\frac{50}{3}\right)\,\textrm{hrs}=30\,\textrm{hrs}$.


## The speed of light

* Let's now just confirm that the Lorentz transform preserves the speed of light.
* In the unprimed frame, a photon is sent at $t=0$ in the $+x$ direction and strikes a receptor at $t=t_0$, position $x=ct_0$.
* In the primed frame:
	* $x'=\gamma(x-vt)=\gamma(ct_0-vt_0)=\gamma (c-v) t_0$.
	* $t'=\gamma(t-\frac{vx}{c^2})=\gamma(t_0-\frac{vt_0}{c})=\gamma (1-(v/c)) t_0$.

## The speed of light

In the primed frame:

$$
\begin{align*}
\frac{x'}{t'}&\class{fragment}{{}=\frac{\gamma (c-v) t_0}{\gamma (1-(v/c)) t_0}}\\
&\class{fragment}{{}=\frac{(c-v) }{1-(v/c)}}\\
&\class{fragment}{{}=\frac{c(1-(v/c)) }{1-(v/c)}}\\
&\class{fragment}{{}=c}\\
\end{align*}
$$

## Conclusion

* We now have a rote, mindless way to convert between different frames’ coordinates.
* Furthermore, the Lorentz transform is “just” a pair of linear equations, of the form $x'=Ax+Bt$ and $t'=Cx+Dt$.

## Conclusion

* We can plot events on a graph with $x$ on the horizontal axis and $ct$ on the vertical axis. Ponder:
	* What path do photons trace out on this graph? How does the path of a photon change from frame to frame? (Hint: it shouldn't change speed!)
   * In a given frame, simultaneous events lie on a horizontal line. What do those same events look like in a frame with relative velocity $v$?
	* In a given frame, co-located events lie on a vertical line. What do those same events look like in a frame with relative velocity $v$?

## Conclusion

::: {.r-stack}

<iframe src="../special-relativity-lessons/lesson-4/SpacetimeDiagram" width="1400" height="600" frameborder="true" ></iframe>

:::
