---
title: "Lesson 3.2: Length Contraction"
format: revealjs
---

# Recap

## Time dilation

* If I'm watching a person move relative to me, whose clock do I perceive to run slower: mine or theirs?
* Whose clock do they perceive to run slower: mine or theirs?
* By what factor?
  * $\gamma = \frac{1}{\sqrt{1-(v/c)^2}}$

## Synchronization

* What does it mean to synchronize clocks?
* How did we synchronize clocks?
* Now that we have synchronized clocks, what can we do that we couldn't do before?

## Time of travel

* FAQ: when we record the time of a distant event, are we referring to when it “actually” happened or when we saw it happen? [The latter incurs a delay due to the time it takes light to reach us from the event.]{.fragment}
* Answer: when it “actually” happened. [We know how far away it is, so we know how long it took the light to reach us.]{.fragment}
* So whenever we talk about the time of an event, we're always talking about the time a stationary clock located there (and synced with us) would have read when the event occurred.

::: {.notes}
Let's say an event happens one light second away from me, and I observe its light reach me at t=5s. Then I know the event took place at t=4s.
:::

# Now, back to the train

## Train observers

* We put _two_ observers on the train, one at the front (Frank) and one at the back (Beth).
  * And ensure their clocks are synchronized!
* When I (on the platform) pass by the front of the train, Frank records the time on his clock and the time he reads on my clock.
* When I pass by the back of the train, Beth records the time on her clock and the time she reads on my clock.

## Their time measurement

* Afterwards, Frank and Beth reconvene. [What is the difference they observe between when I pass by Frank and when I pass by Beth?]{.fragment}
* To those on the train, it takes $\Delta t'=\frac{L}{v}$ for me to move from the front of the train to the back, so that's what the time difference is on _their_ two clocks.
* But they think my clock runs slow by a factor of $\gamma$! [So the difference between Frank’s reading of my clock and Beth’s reading of my clock will be $\Delta t=\frac{\Delta t'}{\gamma}=\frac{L}{\gamma v}$.]{.fragment}

## My time measurement

* Key point: [Frank and Beth were at the same place and time as me when they saw my clock...]{.fragment} [so that's _also what I'll read on my clock_.]{.fragment}
  * Remember — no privileged reference frames. If two observers are in the same spot at the same time, they agree on the state of things there and then.
  * More precisely, if one observer says two events are the same, all observers agree.
  * Beth says that when she passes me, my clock reads $\frac{L}{\gamma v}$, [and therefore I must agree!]{.fragment}

## My length measurement

* So from my perspective, the front of the train is now $v\Delta t=v\cdot\frac{L}{\gamma v}=\frac{L}{\gamma}$ from me.
* And that's the length of the train (to me).
* The train is shorter by a factor of $\gamma$!

## Conclusion

* Objects in motion appear contracted by a factor of $\gamma$ along their direction of motion.
* Another contradiction? [Two trains with the same rest length travel past each other — each perceives the other as being shorter.]{.fragment}

## Contracted lengthwise?

* Why only along their direction of motion? Why not in every direction?
  * E.g. why would a train appear squashed from front to back but not top to bottom or left to right?
  * As always, let's devise an experiment that would violate the axioms of relativity.

## Contracted lengthwise

* Supposing that objects in motion appeared contracted in all three dimensions...
* Suppose a train were traveling towards a tunnel exactly big enough for the train to fit when both are at rest relative to each other.
* Set the train in motion.

## Contracted lengthwise

* From the train’s perspective, the tunnel shrinks and is now too small for the train to fit.
* From the tunnel’s perspective, the train shrinks and can now fit with room to spare.
* What happens when the train reaches the tunnel: [does it crash or fly through?]{.fragment}
* The tunnel and train must agree, but they don't — contradiction!

<!-- ## Exercise (5–10 minutes)

* A space probe will be sent to Io to record some data.
* The probe travels from Earth at a constant speed of $\frac{4}{5}c$. According to a clock on the probe, at this speed it takes ten hours to travel from Earth to Io.
* When the probe arrives at Io, it sends a single photon back to Earth to let us know it arrived safely.
* Q: According to us on Earth, how many hours after the probe leaves Earth should we expect the photon to arrive?

::: {.notes}
We mentioned before that there is no such thing as a truly inertial reference frame in our universe, but here, assume that the Earth and Io are stationary relative to each other and are not accelerating.

Also, as stated, the space probe is launched, but if it makes you feel better you can imagine that it's always been traveling at (4/5)c and that ten hours starts when it passes by Earth.
:::

## Solution

* The probe travels for $t'=10\,\textrm{hrs}$ at $v=\frac{4}{5}c$, so it perceives the distance between Earth and Io to be $l'=t'v=10\,\textrm{hrs}\cdot \frac{4}{5}c$.
* But the probe perceives the distance between Earth and Io (which are moving relative to it) as length-contracted.
  * Earth observers would see that same distance as $l=l'\gamma=10\,\textrm{hrs}\cdot \frac{4}{5}c\cdot \frac{5}{3}=\frac{40}{3}\,\textrm{hrs}\cdot c$.

## Solution

* For the probe to travel that distance would take $t_1=l/v=\frac{(40/3)\,\textrm{hrs}\cdot c}{(4/5)\,c}=\frac{50}{3}\,\textrm{hrs}$.
* For the photon to travel that distance would take $t_2=l/c=\frac{(40/3)\,\textrm{hrs}\cdot c}{c}=\frac{40}{3}\,\textrm{hrs}$.
* And so the total time is $t_1+t_2=\frac{90}{3}\,\textrm{hrs}=30\,\textrm{hrs}$. -->

## Special topic: muons

* Subatomic particle similar to the electron except 200x more massive. When observed in the lab, their average lifespan is about $2.2\upmu\textrm{s}$.
* _Secondary muons_ are generated by cosmic rays hitting the upper atmosphere (roughly $15\,\textrm{km}$ up).
* They travel at roughly $0.999c$ and can be detected even underground.
* At this speed, it takes muons roughly $50\upmu\textrm{s}$ to travel through the whole atmosphere.
* Q: How do they survive that long?

::: {.notes}
Let's use relativity to explain this phenomenon.

Two things that are not the answer:

1. The average lifetime is short, but some muons get lucky and last a long time.
   * True, but statistically, there wouldn't be as many muons reaching the ground as we observe.
1. Some get generated right at the bottom of the atmosphere and don't have to travel so far
   * True, but statistically, there wouldn't be as many muons reaching the ground as we observe.
1. A combination of these.
   * True, but...
:::

## Special topic: muons

* What do we see?
* What do the muons see?
* (These need to be in accord with each other.)

## Our perspective

* For these muons, $\gamma=\frac{1}{\sqrt{1-0.999^2}}\approx 22.4$.
* And so their average lifespan _to us_ is $22.4\times 2.2\upmu\textrm{s}=49.3\upmu\textrm{s}$.
* Enough for a healthy fraction of muons to be detected!

## The muons’ perspective

* Meanwhile, the muons think the distance to the ground is $\frac{15\,\textrm{km}}{22.4}=0.67\,\textrm{km}$.
* And with the Earth rushing at a muon at $0.999c$, it would take $2.2\upmu\textrm{s}$ for the Earth to reach it.
* Again, enough for a healthy fraction of muons to be detected!

::: {.notes}
Remember, we said they needed to survive 50µs to make it to the ground.
:::

## For next time

* Make sure you are comfortable with the concepts of:
  * Clock synchronization
  * The derivation of length contraction
  * The way time dilation and length contraction interact to produce a perfectly consistent picture between reference frames.
